depends:
    - test-runner
    - uCOS-III
    - platform-abstraction
    - serializer

source:
    - src/kalman.c
    - src/positioning.c
    - src/beacon_angles.c

target.arm:
    - src/main.c
    - src/runtime.c

templates:
    Makefile.jinja: Makefile

tests:
    - tests/positioning_test.cpp
    - tests/kalman_test.cpp
    - tests/beacon_angles_test.cpp
